// Generated by: task version:sync — edit version.json, then sync.
import Foundation

public enum AppVersion {
  /// User-facing semver (e.g. 0.2.0)
  public static let marketing = "0.6.2"
  /// Build number (integer, increments per release)
  public static let build = 22
  /// Display string for About / diagnostics
  public static var full: String { "\(marketing) (\(build))" }
}
